version: '3.7'
services:
  mysql:
    container_name: diplomaDB
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=mysql
  diploma:
      container_name: diplomaAPP
      image: 'app'
      build:
        context: .
      ports:
        - '5500:5500'